import json
import os

# SEO translations
seo_translations = {
    'en': {
        'default_title': 'brennholzkaufen - Quality Firewood | Fast Delivery',
        'default_description': 'Sale of quality firewood. Logs, pellets and wood pellets delivered to your home. Fast and professional service.'
    },
    'de': {
        'default_title': 'brennholzkaufen - Qualitäts-Brennholz | Schnelle Lieferung',
        'default_description': 'Verkauf von hochwertigem Brennholz. Scheite, Pellets und Holzpellets direkt zu Ihnen nach Hause geliefert. Schneller und professioneller Service.'
    },
    'es': {
        'default_title': 'brennholzkaufen - Leña de Calidad | Entrega Rápida',
        'default_description': 'Venta de leña de calidad. Troncos, pellets y gránulos de madera entregados en su hogar. Servicio rápido y profesional.'
    },
    'it': {
        'default_title': 'brennholzkaufen - Legna di Qualità | Consegna Rapida',
        'default_description': 'Vendita di legna da ardere di qualità. Tronchi, pellet e pellet di legno consegnati a casa tua. Servizio rapido e professionale.'
    },
    'nl': {
        'default_title': 'brennholzkaufen - Kwaliteitsbrandhout | Snelle Levering',
        'default_description': 'Verkoop van kwaliteitsbrandhout. Blokken, pellets en houtpellets bij u thuis bezorgd. Snelle en professionele service.'
    },
    'pt': {
        'default_title': 'brennholzkaufen - Lenha de Qualidade | Entrega Rápida',
        'default_description': 'Venda de lenha de qualidade. Troncos, pellets e pellets de madeira entregues em sua casa. Serviço rápido e profissional.'
    }
}

# PDF translations
pdf_translations = {
    'en': {
        'order': 'Order', 'date': 'Date', 'status': 'Status',
        'delivery_address': 'Delivery address', 'phone': 'Phone',
        'article': 'Item', 'qty': 'Qty', 'unit_price': 'Unit Price',
        'total': 'Total', 'subtotal': 'Subtotal', 'delivery': 'Delivery',
        'thank_you': 'Thank you for your trust.',
        'auto_generated': 'Document automatically generated by brennholzkaufen.',
        'invoice': 'invoice'
    },
    'de': {
        'order': 'Bestellung', 'date': 'Datum', 'status': 'Status',
        'delivery_address': 'Lieferadresse', 'phone': 'Tel',
        'article': 'Artikel', 'qty': 'Menge', 'unit_price': 'Stückpreis',
        'total': 'Gesamt', 'subtotal': 'Zwischensumme', 'delivery': 'Lieferung',
        'thank_you': 'Vielen Dank für Ihr Vertrauen.',
        'auto_generated': 'Dokument automatisch generiert von brennholzkaufen.',
        'invoice': 'rechnung'
    },
    'es': {
        'order': 'Pedido', 'date': 'Fecha', 'status': 'Estado',
        'delivery_address': 'Dirección de entrega', 'phone': 'Tel',
        'article': 'Artículo', 'qty': 'Cant.', 'unit_price': 'Precio Unit.',
        'total': 'Total', 'subtotal': 'Subtotal', 'delivery': 'Entrega',
        'thank_you': 'Gracias por su confianza.',
        'auto_generated': 'Documento generado automáticamente por brennholzkaufen.',
        'invoice': 'factura'
    },
    'it': {
        'order': 'Ordine', 'date': 'Data', 'status': 'Stato',
        'delivery_address': 'Indirizzo di consegna', 'phone': 'Tel',
        'article': 'Articolo', 'qty': 'Qtà', 'unit_price': 'Prezzo Unit.',
        'total': 'Totale', 'subtotal': 'Subtotale', 'delivery': 'Consegna',
        'thank_you': 'Grazie per la vostra fiducia.',
        'auto_generated': 'Documento generato automaticamente da brennholzkaufen.',
        'invoice': 'fattura'
    },
    'nl': {
        'order': 'Bestelling', 'date': 'Datum', 'status': 'Status',
        'delivery_address': 'Bezorgadres', 'phone': 'Tel',
        'article': 'Artikel', 'qty': 'Aantal', 'unit_price': 'Eenheidsprijs',
        'total': 'Totaal', 'subtotal': 'Subtotaal', 'delivery': 'Levering',
        'thank_you': 'Bedankt voor uw vertrouwen.',
        'auto_generated': 'Document automatisch gegenereerd door brennholzkaufen.',
        'invoice': 'factuur'
    },
    'pt': {
        'order': 'Encomenda', 'date': 'Data', 'status': 'Estado',
        'delivery_address': 'Endereço de entrega', 'phone': 'Tel',
        'article': 'Artigo', 'qty': 'Qtd', 'unit_price': 'Preço Unit.',
        'total': 'Total', 'subtotal': 'Subtotal', 'delivery': 'Entrega',
        'thank_you': 'Obrigado pela sua confiança.',
        'auto_generated': 'Documento gerado automaticamente por brennholzkaufen.',
        'invoice': 'fatura'
    }
}

base_path = 'apps/client/src/i18n/locales'

for lang in ['en', 'de', 'es', 'it', 'nl', 'pt']:
    file_path = os.path.join(base_path, lang, 'translation.json')
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        # Add SEO translations
        if 'seo' not in data:
            data['seo'] = seo_translations[lang]
        
        # Add PDF translations
        if 'suivi' not in data:
            data['suivi'] = {}
        if 'pdf' not in data['suivi']:
            data['suivi']['pdf'] = pdf_translations[lang]
        
        # Write back
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        
        print(f'✅ Updated {lang}/translation.json')
    except Exception as e:
        print(f'❌ Error updating {lang}: {e}')

print('\n✅ All translations updated!')
